import { getServerSession } from "next-auth"; // Example for NextAuth
import Header from "./components/layout/Header";
import type { Metadata } from "next";
import AppProvider from './components/AppContext';
import "./globals.css";
import { Roboto } from "next/font/google";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(); // Fetch the session

  return (
    <html lang="en">
      <body className={`${roboto.variable} antialiased`}>
        <main className="max-w-4xl mx-auto p-4">
          <AppProvider session={session}>
            <Header />
            {children}
            <footer className="border-t p-8 text-center text-gray-500 mt-16">
              &copy; 2025 All Rights Reserved
            </footer>
          </AppProvider>
        </main>
      </body>
    </html>
  );
}
